### ISSUE TITLE
Requirement and Installation

### ISSUE THREAD

**Issue by iambudi** [waterguo/antsdb#14]
Hi,
Curious to try antsdb. I use binary download. My macbook meets the h/w requirement. When i run it's failed with the following error log:

```
02 12:16:23,128 [WrapperSimpleAppMain] ERROR server.SaltedFish - failed to start
java.lang.NullPointerException
	at com.antsdb.saltedfish.storage.HBaseStorageService.open(HBaseStorageService.java:156)
	at com.antsdb.saltedfish.nosql.Humpback.initStorage(Humpback.java:296)
	at com.antsdb.saltedfish.nosql.Humpback.init(Humpback.java:249)
	at com.antsdb.saltedfish.nosql.Humpback.open(Humpback.java:195)
	at com.antsdb.saltedfish.sql.Orca.<init>(Orca.java:132)
	at com.antsdb.saltedfish.server.SaltedFish.startDatabase(SaltedFish.java:137)
	at com.antsdb.saltedfish.server.SaltedFish.start(SaltedFish.java:54)
	at com.antsdb.saltedfish.server.SaltedFish.run(SaltedFish.java:133)
	at com.antsdb.saltedfish.server.SaltedFishMain.run(SaltedFishMain.java:83)
	at com.antsdb.saltedfish.server.SaltedFishMain.main(SaltedFishMain.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:240)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Any other requirement other than installing hadoop and hbase  before setup antsdb?

**Comment by iambudi** [comment]
antsdb-check result :
```
antsdb home: /Users/budi/Applications/antsdb
antsdb configuration: /Users/budi/Applications/antsdb/conf/conf.properties
storage: hbase
hbase config: /usr/local/Cellar/hbase/1.2.9/libexec/conf/hbase-site.xml
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.antsdb.saltedfish.util.UberUtil (file:/Users/budi/Applications/antsdb/lib/antsdb-all.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.antsdb.saltedfish.util.UberUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
zookeeper quorum: localhost
error: unable to connect to quorum
```

**Comment by waterguo** [comment]
It means antsdb is unable to connect to hbase. One thing i noticed is you are using "localhost" in your hbase-site.xml. Using "localhost" often causes many strange issues in hadoop stack. I would suggest you to use the real hostname.

By the way, are you using a hadoop distribution?

**Comment by iambudi** [comment]
My apologies i'm newbie to hbase/hadoop stuff. 
How to check if hbase runs okay and can be connected from antsdb since the hbase shell runs well.
I tried to create a localhost map to 127.0.0.0 with `local.hbase.com`.

The same error log:
```
20:25:53,484 [WrapperSimpleAppMain] ERROR server.SaltedFish - failed to start
java.lang.NullPointerException
	at com.antsdb.saltedfish.storage.HBaseStorageService.open(HBaseStorageService.java:156)
	at com.antsdb.saltedfish.nosql.Humpback.initStorage(Humpback.java:296)
	at com.antsdb.saltedfish.nosql.Humpback.init(Humpback.java:249)
	at com.antsdb.saltedfish.nosql.Humpback.open(Humpback.java:195)
	at com.antsdb.saltedfish.sql.Orca.<init>(Orca.java:132)
	at com.antsdb.saltedfish.server.SaltedFish.startDatabase(SaltedFish.java:137)
	at com.antsdb.saltedfish.server.SaltedFish.start(SaltedFish.java:54)
	at com.antsdb.saltedfish.server.SaltedFish.run(SaltedFish.java:133)
	at com.antsdb.saltedfish.server.SaltedFishMain.run(SaltedFishMain.java:83)
	at com.antsdb.saltedfish.server.SaltedFishMain.main(SaltedFishMain.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:240)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

> By the way, are you using a hadoop distribution?
I installed hadoop from brew.

**Comment by waterguo** [comment]
I will write an short instructions about how to setup a minimal hbase/antsdb environment for testing below. 

1. Download the hbase binary and extract it. In my case, I've downloaded the latest 2.1.4 release and extracted it to **/Users/xinyi/opt/hbase-2.1.4**

2. Start the hbase in standalone mode by execute **/Users/xinyi/opt/hbase-2.1.4/bin/start-hbase**

3. Verify that hbase works. Execute **/Users/xinyi/opt/hbase-2.1.4/bin/hbase shell**. If you don't see any errors, everything works.

4. Download the latest antsdb release extract it. In my case, it is in folder **/Users/xinyi/opt/antsdb**

5. Create the configuration file. Go to folder **/Users/xinyi/opt/antsdb/conf**. Execute **conf.properties.template conf.properties**

6. Edit the file **conf.properties**. Find the line starting with **humpback.hbase-conf=**. Now enter the **absolute path** of the **hbase-site.xml** file from the **hbase** folder. It my case, it is **/Users/xinyi/opt/hbase-2.1.4/conf/hbase-site.xml**

7. Check if it works. Go to the antsdb bin folder, run **hbase-check**. You should see no errors.

8. You can now start antsdb. Everything should work.

Let me know if you still have issues. Steps above should work on both Mac and Linux.

water

**Comment by iambudi** [comment]
It showed the same error and few warnings. Since that's the similiar steps i did before. 

I was wondering if JDK version is the issue since i use JDk 11. When i check in antsdb download page the System Requirements of Java should be 1.8, my bad :). 
After switching it works perfectly, no error, no warning. Thank you so much :)

Btw, why does antsdb require 100 GB storage?

**Comment by waterguo** [comment]
Good to know it works now. 100GB is used to cache the records from HBase. By default, the max. size of the cache is 100GB. But if you database is less than 100GB, it won't be using that much.
