### ISSUE TITLE
Part of the sql function does not support

### ISSUE THREAD

**Issue by xiaokuis** [waterguo/antsdb#3]
Part of the sql function does not support，E.g：concat after like

com.antsdb.saltedfish.sql.OrcaException: Invalid SQL. Offending token: concat
        at com.antsdb.saltedfish.sql.Session.parse(Session.java:214)
        at com.antsdb.saltedfish.sql.Session.run(Session.java:113)
        at com.antsdb.saltedfish.server.mysql.QueryHandler.query(QueryHandler.java:46)
        at com.antsdb.saltedfish.server.mysql.MysqlSession.query(MysqlSession.java:305)
        at com.antsdb.saltedfish.server.mysql.MysqlSession.run0(MysqlSession.java:170)
        at com.antsdb.saltedfish.server.mysql.MysqlSession.run(MysqlSession.java:117)
        at com.antsdb.saltedfish.server.SimpleSocketWorker.run0(SimpleSocketWorker.java:90)
        at com.antsdb.saltedfish.server.SimpleSocketWorker.run(SimpleSocketWorker.java:61)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.antlr.v4.runtime.misc.ParseCancellationException
        at org.antlr.v4.runtime.BailErrorStrategy.recover(BailErrorStrategy.java:75)
        at com.antsdb.saltedfish.lexer.MysqlParser.like_expr(MysqlParser.java:12236)
        at com.antsdb.saltedfish.lexer.MysqlParser.expr(MysqlParser.java:11708)
        at com.antsdb.saltedfish.lexer.MysqlParser.expr(MysqlParser.java:11649)
        at com.antsdb.saltedfish.lexer.MysqlParser.where_clause(MysqlParser.java:7579)
        at com.antsdb.saltedfish.lexer.MysqlParser.select_or_values(MysqlParser.java:7294)
        at com.antsdb.saltedfish.lexer.MysqlParser.select_stmt(MysqlParser.java:7010)
        at com.antsdb.saltedfish.lexer.MysqlParser.from_subquery(MysqlParser.java:8532)
        at com.antsdb.saltedfish.lexer.MysqlParser.from_item(MysqlParser.java:8179)
        at com.antsdb.saltedfish.lexer.MysqlParser.from_clause(MysqlParser.java:7433)
        at com.antsdb.saltedfish.lexer.MysqlParser.select_or_values(MysqlParser.java:7285)
        at com.antsdb.saltedfish.lexer.MysqlParser.select_stmt(MysqlParser.java:7010)
        at com.antsdb.saltedfish.lexer.MysqlParser.sql_stmt(MysqlParser.java:700)
        at com.antsdb.saltedfish.lexer.MysqlParser.script(MysqlParser.java:363)
        at com.antsdb.saltedfish.sql.mysql.MysqlParserFactory.parse(MysqlParserFactory.java:120)
        at com.antsdb.saltedfish.sql.mysql.MysqlParserFactory.parse(MysqlParserFactory.java:54)
        at com.antsdb.saltedfish.sql.Session.parse(Session.java:202)
        ... 10 more
Caused by: org.antlr.v4.runtime.NoViableAltException
        at com.antsdb.saltedfish.lexer.MysqlParser.like_expr(MysqlParser.java:12230)

**Comment by waterguo** [comment]
Hi, xiaokuis,

AntsDB does support concat. For example, I just verified "select concat('abc', '123') as result" does work as expected. If you could post the query that caused the error, I will look into it.

zerofill has not been implemented yet. I will add it soon.

Thanks
~water

**Comment by waterguo** [comment]
ZEROFILL is added in 18.07.27 release, Below is the test result

```
MySQL [test]> create table test (id int(8) zerofill, value int(8));
Query OK, 0 rows affected (0.01 sec)
MySQL [test]> INSERT INTO test VALUES (1, 1);
Query OK, 1 row affected (0.02 sec)
MySQL [test]> SELECT * FROM test;
+----------+-------+
| id       | value |
+----------+-------+
| 00000001 |     1 |
+----------+-------+
1 row in set (0.00 sec)
```

**Comment by waterguo** [comment]
concat() in LIKE is fixed. Below is the test result

```
MySQL [(none)]> SELECT * FROM DUAL WHERE 'abc' LIKE concat('%', 'c');
+-------+
| DUMMY |
+-------+
| X     |
+-------+
1 row in set (0.00 sec)
```
